apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: banana
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: banana
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: banana
        image: cs4783registry.azurecr.io/banana:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 12600
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: lb-banana
spec:
  type: LoadBalancer
  ports:
  - port: 12600
  selector:
    app: banana
